version: '3.8'

services:
  headless-chromium:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.chromium
    ports:
      - "9222:9222"
    restart: unless-stopped
    command: ["chromium", "--remote-debugging-port=9222", "--remote-debugging-address=0.0.0.0", "--disable-dev-shm-usage", "--no-sandbox", "--headless"]