version: "3.8"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ~/storage/gitea/data:/data
      - ~/storage/gitea/etc/timezone:/etc/timezone:ro
      - ~/storage/gitea/etc/localtime:/etc/localtime:ro
    ports:
      - "8000:3000"
      - "222:22"