version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ~/stoage/mongodb/data/db:/data/db

volumes:
  mongodb_data:
    driver: local