FROM ubuntu:latest

WORKDIR /app

RUN apt update && apt install -y python3 python3-pip python3-venv nvidia-cuda-toolkit libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++

RUN pip3 install torch torchvision torchaudio matplotlib scipy numpy pylzma ipykernel jupyter

COPY requirements.txt .

RUN python3 -m pip install -r requirements.txt

RUN python3 -m ipykernel install --user --name=cuda --display-name "cuda-gpt"

