FROM ubuntu:latest
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

WORKDIR /app

RUN apt update && apt install -y python3 \
    python3-pip \
    python3-venv \
    nvidia-cuda-toolkit \
    build-essential \
    git \
    wget

COPY requirements.txt .

RUN pip3 install -r requirements.txt

RUN useradd -ms /bin/bash newuser
RUN chown -R newuser /app
