version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.jupyter
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    restart: unless-stopped
    ports:
      - ${JUPYTER_EXTERNAL_PORT}:8000
    volumes:
      - ${DOCS_DIR}:/app/docs
      - ${NOTEBOOKS_DIR}:/app/notebooks
      - ${TRAINING_DIR}:/app/training
      - ${MODELS_DIR}:/app/models
      - ${EXTENSIONS_DIR}:/app/extensions
    user: newuser
    command: python3 -m jupyter lab --ip=0.0.0.0 --port=8000