from ubuntu:latest
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt update && apt dist-upgrade -y

WORKDIR /app

RUN apt update && apt install -y python3 \
    python3-pip \
    python3-venv \
    nvidia-cuda-toolkit \
    build-essential \
    git \
    wget

RUN useradd -ms /bin/bash newuser
RUN chown -R newuser /app