version: '3.8'

services:
  transformers:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.transformers
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    restart: unless-stopped
    ports:
      - ${TF_EXTERNAL_PORT}:8000
    volumes:
      - ${TF_DIRECTORY}:${INTERNAL_APP_DIRECTORY}
      - ${LOCAL_MODEL_DIRECTORY}:${INTERNAL_TF_MODEL_DIRECTORY}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - HF_MODEL=${HF_MODEL}
      - HF_TOKEN=${HF_TOKEN}
      - LOAD_IN_4BIT=${LOAD_IN_4BIT}
      - LOAD_IN_8BIT=${LOAD_IN_8BIT}
    command: uvicorn --host 0.0.0.0 --port 8000 main:app
